<a href="https://colab.research.google.com/github/sapienology/First-Repo/blob/main/Car%20Prices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [81]:
import pandas as pd

In [82]:
df1 = pd.read_csv('/content/cars.csv')

In [83]:
df1

,Car_ID,Brand,Model,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price
0,1,Toyota,Corolla,2018,50000,Petrol,Manual,First,15,1498,108,5,800000
1,2,Honda,Civic,2019,40000,Petrol,Automatic,Second,17,1597,140,5,1000000
2,3,Ford,Mustang,2017,20000,Petrol,Automatic,First,10,4951,395,4,2500000
3,4,Maruti,Swift,2020,30000,Diesel,Manual,Third,23,1248,74,5,600000
4,5,Hyundai,Sonata,2016,60000,Diesel,Automatic,Second,18,1999,194,5,850000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,Mercedes,C-Class,2019,22000,Diesel,Automatic,First,16,1950,191,5,2900000
96,97,Toyota,Innova Crysta,2017,38000,Diesel,Manual,Second,13,2755,171,7,1400000
97,98,Ford,EcoSport,2018,26000,Petrol,Manual,Third,18,1497,121,5,750000
98,99,Hyundai,Verna,2019,24000,Petrol,Automatic,Second,17,1497,113,5,850000
99,100,Tata,Altroz,2020,18000,Petrol,Manual,First,20,1199,85,5,600000

In [84]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Car_ID             100 non-null    int64
 1   Brand              100 non-null    object
 2   Model              100 non-null    object
 3   Year               100 non-null    int64
 4   Kilometers_Driven  100 non-null    int64
 5   Fuel_Type          100 non-null    object
 6   Transmission       100 non-null    object
 7   Owner_Type         100 non-null    object
 8   Mileage            100 non-null    int64
 9   Engine             100 non-null    int64
 10  Power              100 non-null    int64
 11  Seats              100 non-null    int64
 12  Price              100 non-null    int64
dtypes: int64(8), object(5)
memory usage: 10.3+ KB

In [85]:
df1.isna().sum()

Car_ID               0
Brand                0
Model                0
Year                 0
Kilometers_Driven    0
Fuel_Type            0
Transmission         0
Owner_Type           0
Mileage              0
Engine               0
Power                0
Seats                0
Price                0
dtype: int64

THE MODEL COLUMN

In [86]:
df1['Model'].unique()

array(['Corolla', 'Civic', 'Mustang', 'Swift', 'Sonata', 'Nexon',
       'Scorpio', 'Polo', 'A4', 'X1', 'C-Class', 'Endeavour', 'Creta',
       'Harrier', 'Ertiga', 'City', 'Tiguan', 'Q3', '5 Series', 'GLC',
       'Innova', 'Figo', 'Verna', 'Altroz', 'Thar', 'Passat', 'A6', 'X3',
       'E-Class', 'Fortuner', 'Aspire', 'Elantra', 'Safari', 'Vitara',
       'WR-V', 'Ameo', 'A3', '7 Series', 'GLE', 'Yaris', 'Ranger',
       'Santro', 'Tigor', 'S-Cross', 'BR-V', 'T-Roc', 'Q7', 'X5', 'GLA',
       'Camry', 'Venue', 'Tiago', 'XUV300', 'Vento', 'A5', '3 Series',
       'Innova Crysta', 'EcoSport'], dtype=object)

In [87]:
from sklearn.preprocessing import LabelEncoder

In [88]:
#df1['Model'] = df1['Model'].astype(str).str.strip()

In [89]:
inte = LabelEncoder()

In [90]:
df1['Model'] = inte.fit_transform(df1['Model'])

In [91]:
df1['Model']

0     15
1     14
2     30
3     42
4     41
      ..
95    11
96    29
97    18
98    50
99     7
Name: Model, Length: 100, dtype: int64

In [92]:
df1['Model'].astype(int)

0     15
1     14
2     30
3     42
4     41
      ..
95    11
96    29
97    18
98    50
99     7
Name: Model, Length: 100, dtype: int64

THE OWNER TYPE COLUMN

In [93]:
df1['Owner_Type'].unique()

array(['First', 'Second', 'Third'], dtype=object)

In [94]:
df1['Owner_Type'] = df1['Owner_Type'].replace({
'First' : 0 ,
 'Second' : 1 ,
  'Third' : 2
})

/tmp/ipykernel_15311/172527210.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1['Owner_Type'] = df1['Owner_Type'].replace({

In [95]:
df1['Owner_Type'].astype(int)

0     0
1     1
2     0
3     2
4     1
     ..
95    0
96    1
97    2
98    1
99    0
Name: Owner_Type, Length: 100, dtype: int64

THE TRANSMISION COLUMN

In [96]:
df1['Transmission'].unique()

array(['Manual', 'Automatic'], dtype=object)

In [97]:
df1['Transmission'] = df1['Transmission'].replace({
    'Manual' : 0 ,
    'Automatic' : 1
})

/tmp/ipykernel_15311/3326025544.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1['Transmission'] = df1['Transmission'].replace({

In [98]:
df1['Transmission'].astype(int)

0     0
1     1
2     1
3     0
4     1
     ..
95    1
96    0
97    0
98    1
99    0
Name: Transmission, Length: 100, dtype: int64

THE FUEL TYPE COLUMN

In [99]:
df1['Fuel_Type'].unique()

array(['Petrol', 'Diesel'], dtype=object)

In [100]:
df1['Fuel_Type'] = df1['Fuel_Type'].replace({
    'Petrol' : 0 ,
    'Diesel' : 1
})

/tmp/ipykernel_15311/3398916642.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1['Fuel_Type'] = df1['Fuel_Type'].replace({

In [101]:
df1['Fuel_Type'].astype(int)

0     0
1     0
2     0
3     1
4     1
     ..
95    1
96    1
97    0
98    0
99    0
Name: Fuel_Type, Length: 100, dtype: int64

THE YEAR COLUMN

In [102]:
df1['Year'].unique()

array([2018, 2019, 2017, 2020, 2016, 2021])

THE BRAND COLUMN

In [103]:
df1['Brand'].unique()

array(['Toyota', 'Honda', 'Ford', 'Maruti', 'Hyundai', 'Tata', 'Mahindra',
       'Volkswagen', 'Audi', 'BMW', 'Mercedes'], dtype=object)

In [104]:
df1['Brand'] = df1['Brand'].replace({
    'Toyota' : 0 ,
    'Honda'  : 1 ,
    'Ford'   : 2 ,
    'Maruti' : 3 ,
    'Hyundai' : 4 ,
    'Tata'   :   5 ,
    'Mahindra' : 6 ,
    'Volkswagen' : 7,
    'Audi'       : 8 ,
    'BMW'    : 9 ,
    'Mercedes' : 10
})

/tmp/ipykernel_15311/1187921877.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1['Brand'] = df1['Brand'].replace({

In [105]:
df1['Brand'].astype(int)

0      0
1      1
2      2
3      3
4      4
      ..
95    10
96     0
97     2
98     4
99     5
Name: Brand, Length: 100, dtype: int64

In [106]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Car_ID             100 non-null    int64
 1   Brand              100 non-null    int64
 2   Model              100 non-null    int64
 3   Year               100 non-null    int64
 4   Kilometers_Driven  100 non-null    int64
 5   Fuel_Type          100 non-null    int64
 6   Transmission       100 non-null    int64
 7   Owner_Type         100 non-null    int64
 8   Mileage            100 non-null    int64
 9   Engine             100 non-null    int64
 10  Power              100 non-null    int64
 11  Seats              100 non-null    int64
 12  Price              100 non-null    int64
dtypes: int64(13)
memory usage: 10.3 KB

In [107]:
df1 = df1.drop('Car_ID' , axis =1 )

In [108]:
df1

,Brand,Model,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price
0,0,15,2018,50000,0,0,0,15,1498,108,5,800000
1,1,14,2019,40000,0,1,1,17,1597,140,5,1000000
2,2,30,2017,20000,0,1,0,10,4951,395,4,2500000
3,3,42,2020,30000,1,0,2,23,1248,74,5,600000
4,4,41,2016,60000,1,1,1,18,1999,194,5,850000
...,...,...,...,...,...,...,...,...,...,...,...,...
95,10,11,2019,22000,1,1,0,16,1950,191,5,2900000
96,0,29,2017,38000,1,0,1,13,2755,171,7,1400000
97,2,18,2018,26000,0,0,2,18,1497,121,5,750000
98,4,50,2019,24000,0,1,1,17,1497,113,5,850000
99,5,7,2020,18000,0,0,0,20,1199,85,5,600000

In [109]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Brand              100 non-null    int64
 1   Model              100 non-null    int64
 2   Year               100 non-null    int64
 3   Kilometers_Driven  100 non-null    int64
 4   Fuel_Type          100 non-null    int64
 5   Transmission       100 non-null    int64
 6   Owner_Type         100 non-null    int64
 7   Mileage            100 non-null    int64
 8   Engine             100 non-null    int64
 9   Power              100 non-null    int64
 10  Seats              100 non-null    int64
 11  Price              100 non-null    int64
dtypes: int64(12)
memory usage: 9.5 KB

In [110]:
from sklearn.model_selection import train_test_split

In [111]:
X = df1.drop(columns = ['Price'])

In [112]:
Y = df1['Price']

In [113]:
X_train ,X_test,Y_train ,Y_test = train_test_split(X ,Y ,test_size = 0.2 , random_state = 42)

In [114]:
X_train

,Brand,Model,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats
55,8,5,2018,28000,1,1,0,17,1968,187,5
88,2,30,2019,22000,0,1,0,13,2261,396,4
26,8,6,2018,28000,0,1,0,15,1984,241,5
42,5,46,2018,42000,1,0,0,24,1047,69,5
69,4,19,2017,32000,1,1,1,22,1582,126,5
...,...,...,...,...,...,...,...,...,...,...,...
60,4,50,2019,24000,0,1,1,17,1497,113,5
71,3,51,2019,24000,0,0,1,17,1462,103,5
14,3,21,2020,18000,0,0,0,19,1462,103,7
92,7,48,2017,32000,0,0,1,18,1598,103,5
51,4,49,2018,32000,0,0,2,17,1197,81,5

In [115]:
df1['Price'].value_counts()

Price
850000     8
600000     6
650000     6
500000     6
700000     6
2700000    5
1600000    5
750000     5
2800000    4
3200000    4
2500000    4
1800000    3
2000000    3
800000     3
1400000    3
3000000    3
550000     3
1300000    2
1500000    2
450000     2
3500000    2
4000000    2
1200000    2
2600000    2
2400000    2
2900000    2
1900000    1
1000000    1
2300000    1
2200000    1
900000     1
Name: count, dtype: int64

In [116]:
from sklearn.linear_model import LogisticRegression

In [117]:
log = LogisticRegression()

In [118]:
log.fit(X_train,Y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [119]:
pred = log.predict(X_test)

In [120]:
pred

array([ 850000,  750000, 2000000,  850000,  750000,  700000,  850000,
       2000000, 2700000, 2000000, 2700000,  600000,  700000,  850000,
        600000,  900000, 3000000,  700000,  850000,  750000])

In [121]:
Y_test.values

array([1600000,  700000, 1300000, 1600000,  850000,  650000,  850000,
        500000, 2300000,  800000, 3000000,  600000,  500000,  700000,
        500000,  850000, 4000000,  650000,  850000,  800000])

In [122]:
new_df = {'pred' : pred , 'Y_test' :Y_test}

In [123]:
from sklearn.metrics import classification_report

In [124]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

print("MAE:", mean_absolute_error(Y_test, pred))
print("MSE:", mean_squared_error(Y_test, pred))
print("RMSE:", np.sqrt(mean_squared_error(Y_test, pred)))
print("R2:", r2_score(Y_test, pred))

MAE: 370000.0
MSE: 332500000000.0
RMSE: 576628.1297335398
R2: 0.5934462309714496

HYPER PARAMETER TUNING

In [125]:
from sklearn.model_selection import GridSearchCV

In [126]:
log_param = {"C":[0.1,1], "penalty":["l1","l2"]}

In [127]:
grid = GridSearchCV(
    LogisticRegression(),
    log_param
)

In [128]:
grid.fit(X_train,Y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_split.py:805: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py:528: FitFailedWarning:
10 fits failed out of a total of 20.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.12/dist-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py", line 1193, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py", line 63, in _check_solver
    raise ValueError(
ValueError: Solver lbfgs supports only 'l2' or None penalties, got l1 penalty.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_search.py:1108: UserWarning: One or more of the test scores are non-finite: [   nan 0.1625    nan 0.175 ]
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

GridSearchCV(estimator=LogisticRegression(),
             param_grid={'C': [0.1, 1], 'penalty': ['l1', 'l2']})

In [129]:
grid.fit(X_train,Y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_split.py:805: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py:528: FitFailedWarning:
10 fits failed out of a total of 20.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.12/dist-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py", line 1193, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py", line 63, in _check_solver
    raise ValueError(
ValueError: Solver lbfgs supports only 'l2' or None penalties, got l1 penalty.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_search.py:1108: UserWarning: One or more of the test scores are non-finite: [   nan 0.1625    nan 0.175 ]
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

GridSearchCV(estimator=LogisticRegression(),
             param_grid={'C': [0.1, 1], 'penalty': ['l1', 'l2']})

In [130]:
grid.best_estimator_

LogisticRegression(C=1)

In [131]:
grid_pred = grid.predict(X_test)

In [132]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

print("MAE:", mean_absolute_error(Y_test, grid_pred))
print("MSE:", mean_squared_error(Y_test, grid_pred))
print("RMSE:", np.sqrt(mean_squared_error(Y_test, grid_pred)))
print("R2:", r2_score(Y_test, grid_pred))

MAE: 370000.0
MSE: 332500000000.0
RMSE: 576628.1297335398
R2: 0.5934462309714496

SVM

In [133]:
from sklearn import svm

In [134]:
svm_reg = svm.SVR()

In [135]:
svm_reg.fit(X, Y)

SVR()

In [136]:
pred_new_svm = svm_reg.predict(X_test)

In [137]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

print("MAE:", mean_absolute_error(Y_test, pred_new_svm))
print("MSE:", mean_squared_error(Y_test, pred_new_svm))
print("RMSE:", np.sqrt(mean_squared_error(Y_test, pred_new_svm)))
print("R2:", r2_score(Y_test, pred_new_svm))

MAE: 719998.5330552884
MSE: 832248913101.6418
RMSE: 912276.7743956008
R2: -0.017605811703419905

DECISI0N TREES

In [138]:
from sklearn.tree import DecisionTreeRegressor

In [139]:
deci = DecisionTreeRegressor(random_state = 42)

In [140]:
deci.fit(X_train,Y_train)

DecisionTreeRegressor(random_state=42)

In [141]:
pred_new_deci = deci.predict(X_test)

In [142]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

print("MAE:", mean_absolute_error(Y_test, pred_new_deci))
print("MSE:", mean_squared_error(Y_test, pred_new_deci))
print("RMSE:", np.sqrt(mean_squared_error(Y_test, pred_new_deci)))
print("R2:", r2_score(Y_test, pred_new_deci))

MAE: 217500.0
MSE: 176875000000.0
RMSE: 420565.0960315181
R2: 0.7837317356483463

Random Forest

In [143]:
from sklearn.ensemble import RandomForestRegressor

In [144]:
ran = RandomForestRegressor(n_estimators=100, random_state=42)

In [145]:
ran.fit(X , Y)

RandomForestRegressor(random_state=42)

In [146]:
pred_new_ran = ran.predict(X_test)

In [147]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

print("MAE:", mean_absolute_error(Y_test, pred_new_ran))
print("MSE:", mean_squared_error(Y_test, pred_new_ran))
print("RMSE:", np.sqrt(mean_squared_error(Y_test, pred_new_ran)))
print("R2:", r2_score(Y_test, pred_new_ran))

MAE: 61550.0
MSE: 18359175000.0
RMSE: 135496.0331522661
R2: 0.9775519043834444

LINEAR REGRESSION

In [148]:
import numpy as np

In [149]:
from sklearn.linear_model import LinearRegression

In [150]:
reg = LinearRegression().fit(X, Y)

In [151]:
pred_new_reg = reg.predict(X_test)

In [152]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

print("MAE:", mean_absolute_error(Y_test, pred_new_reg))
print("MSE:", mean_squared_error(Y_test, pred_new_reg))
print("RMSE:", np.sqrt(mean_squared_error(Y_test, pred_new_reg)))
print("R2:", r2_score(Y_test, pred_new_reg))

MAE: 269282.9215000838
MSE: 115001961438.29333
RMSE: 339119.3911269206
R2: 0.859385019944619