<a href="https://colab.research.google.com/github/sapienology/First-Repo/blob/main/Copy_of_DIABETES_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
df = pd.read_csv("/content/diabetes_prediction_dataset.csv")

## **EDA**

In [ ]:
df.head()

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0

In [ ]:
df["diabetes"].value_counts()

diabetes
0    91500
1     8500
Name: count, dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   gender               100000 non-null  object
 1   age                  100000 non-null  float64
 2   hypertension         100000 non-null  int64
 3   heart_disease        100000 non-null  int64
 4   smoking_history      100000 non-null  object
 5   bmi                  100000 non-null  float64
 6   HbA1c_level          100000 non-null  float64
 7   blood_glucose_level  100000 non-null  int64
 8   diabetes             100000 non-null  int64
dtypes: float64(3), int64(4), object(2)
memory usage: 6.9+ MB

## Check for unique values

In [ ]:
df["gender"].unique()

array(['Female', 'Male', 'Other'], dtype=object)

In [ ]:
df["smoking_history"].unique()

array(['never', 'No Info', 'current', 'former', 'ever', 'not current'],
      dtype=object)

## Change Datatype

In [ ]:
df['gender'] = df['gender'].replace({'Female': 0, 'Male': 1, 'Other': 2})

/tmp/ipykernel_59056/1753590414.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['gender'] = df['gender'].replace({'Female': 0, 'Male': 1, 'Other': 2})

In [ ]:
df['smoking_history'] = df['smoking_history'].replace({'never': 0, 'No Info': 1, 'current': 2, 'former': 3, 'ever': 4, 'not current': 5})

/tmp/ipykernel_59056/3202853213.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['smoking_history'] = df['smoking_history'].replace({'never': 0, 'No Info': 1, 'current': 2, 'former': 3, 'ever': 4, 'not current': 5})

In [ ]:
df['age'] = df['age'].astype(int)

In [ ]:
df.head()

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,0,80,0,1,0,25.19,6.6,140,0
1,0,54,0,0,1,27.32,6.6,80,0
2,1,28,0,0,0,27.32,5.7,158,0
3,0,36,0,0,2,23.45,5.0,155,0
4,1,76,1,1,2,20.14,4.8,155,0

## Split data

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X = df.drop(columns = ['diabetes'])

In [ ]:
y = df['diabetes']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
X_train

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level
75220,1,73,0,0,3,24.77,3.5,80
48955,1,80,0,0,0,24.60,5.7,145
44966,0,38,0,0,4,24.33,4.0,158
13568,0,26,0,0,5,18.87,5.0,100
92727,0,61,1,0,2,22.11,4.5,85
...,...,...,...,...,...,...,...,...
6265,1,49,0,0,0,32.98,5.7,80
54886,0,15,0,0,0,28.10,5.0,159
76820,1,42,0,0,0,26.14,5.8,85
860,0,37,0,0,0,24.96,6.2,158
15795,0,23,0,0,0,27.99,5.0,159

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
log = LogisticRegression()

In [ ]:
log.fit(X_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [ ]:
pred = log.predict(X_test)

In [ ]:
pred

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
y_test.values

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
new = {"pred": pred, "y_test": y_test}

### **Performance metrics**

In [ ]:
from sklearn.metrics import classification_report

In [ ]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.96      0.99      0.98     18292
           1       0.86      0.60      0.70      1708

    accuracy                           0.96     20000
   macro avg       0.91      0.79      0.84     20000
weighted avg       0.95      0.96      0.95     20000

**HyperParameter Tuning**

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
log_param = {"C":[0.1,1], "penalty":["l1","l2"]}

In [ ]:
grid = GridSearchCV(
    LogisticRegression(),
    log_param
)

In [ ]:
grid.fit(X_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py:528: FitFailedWarning:
10 fits failed out of a total of 20.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.12/dist-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py", line 1193, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py", line 63, in _check_solver
    raise ValueError(
ValueError: Solver lbfgs supports only 'l2' or None penalties, got l1 penalty.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_search.py:1108: UserWarning: One or more of the test scores are non-finite: [      nan 0.9573375       nan 0.9554375]
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

GridSearchCV(estimator=LogisticRegression(),
             param_grid={'C': [0.1, 1], 'penalty': ['l1', 'l2']})

In [ ]:
grid.best_estimator_

LogisticRegression(C=0.1)

In [ ]:
grid_pred = grid.predict(X_test)

In [ ]:
print(classification_report(y_test,grid_pred))

              precision    recall  f1-score   support

           0       0.96      0.99      0.97     18292
           1       0.83      0.56      0.67      1708

    accuracy                           0.95     20000
   macro avg       0.89      0.78      0.82     20000
weighted avg       0.95      0.95      0.95     20000

### **Data Normalization**

In [ ]:
from imblearn.over_sampling import SMOTE

In [ ]:
sm = SMOTE(random_state=42)

In [ ]:
X_resampled, y_resampled = sm.fit_resample(X,y)

In [ ]:
y_resampled.value_counts()

diabetes
0    91500
1    91500
Name: count, dtype: int64

In [ ]:
X_train_new, X_test_new, y_train_new, y_test_new = train_test_split(X_resampled,y_resampled,test_size=0.2,random_state=42)

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
scaler = MinMaxScaler()

In [ ]:
#from sklearn.preprocessing import StandardScaler

In [ ]:
#scaler = StandardScaler()

In [ ]:
scaled_X_train = scaler.fit_transform(X_train_new)

In [ ]:
scaled_X_test = scaler.transform(X_test_new)

In [ ]:
logistic = LogisticRegression()

In [ ]:
logistic.fit(scaled_X_train,y_train_new)

LogisticRegression()

In [ ]:
pred_new = logistic.predict(scaled_X_test)

In [ ]:
print(classification_report(y_test_new,pred_new))

              precision    recall  f1-score   support

           0       0.89      0.88      0.89     18293
           1       0.88      0.89      0.89     18307

    accuracy                           0.89     36600
   macro avg       0.89      0.89      0.89     36600
weighted avg       0.89      0.89      0.89     36600

# Using SVM

In [ ]:
from sklearn import svm

In [ ]:
clf = svm.SVC()

In [ ]:
clf.fit(scaled_X_train,y_train_new)

SVC()

In [ ]:
pred_new_svm = clf.predict(scaled_X_test)

In [ ]:
print(classification_report(y_test_new,pred_new_svm))

              precision    recall  f1-score   support

           0       0.92      0.88      0.90     18293
           1       0.89      0.92      0.90     18307

    accuracy                           0.90     36600
   macro avg       0.90      0.90      0.90     36600
weighted avg       0.90      0.90      0.90     36600

# Decision Trees

In [ ]:
from sklearn import tree

In [ ]:
dt_clf = tree.DecisionTreeClassifier(random_state = 42)

In [ ]:
dt_clf.fit(scaled_X_train,y_train_new)

DecisionTreeClassifier(random_state=0)

In [ ]:
pred_new_dt = dt_clf.predict(scaled_X_test)

In [ ]:
print(classification_report(y_test_new,pred_new_dt))

              precision    recall  f1-score   support

           0       0.98      0.97      0.97     18293
           1       0.97      0.98      0.97     18307

    accuracy                           0.97     36600
   macro avg       0.97      0.97      0.97     36600
weighted avg       0.97      0.97      0.97     36600

# Random Forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
ran = RandomForestClassifier(n_estimators=100, random_state=0)

In [ ]:
X = scaled_X_train
Y = y_train_new

In [ ]:
ran.fit(X , Y)

RandomForestClassifier(random_state=0)

In [ ]:
pred_new_ran = ran.predict(scaled_X_test)

In [ ]:
print(classification_report(y_test_new,pred_new_ran))

              precision    recall  f1-score   support

           0       0.97      0.97      0.97     18293
           1       0.97      0.97      0.97     18307

    accuracy                           0.97     36600
   macro avg       0.97      0.97      0.97     36600
weighted avg       0.97      0.97      0.97     36600

In [ ]:
from sklearn.naive_bayes import GaussianNB

In [ ]:
X = scaled_X_train
Y = y_train_new

In [ ]:
nav = GaussianNB()

In [ ]:
nav.fit(X,Y)

GaussianNB()

In [ ]:
pred_new_nav = nav.predict(scaled_X_test)

In [ ]:
print(classification_report(y_test_new,pred_new_nav))

              precision    recall  f1-score   support

           0       0.82      0.87      0.85     18293
           1       0.87      0.81      0.84     18307

    accuracy                           0.84     36600
   macro avg       0.84      0.84      0.84     36600
weighted avg       0.84      0.84      0.84     36600

In [ ]:
from sklearn.linear_model import SGDClassifier

In [ ]:
X = scaled_X_train
Y = y_train_new

In [ ]:
sgd = SGDClassifier(loss="hinge", penalty="l2", max_iter=5)

In [ ]:
sgd.fit(X, Y)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_stochastic_gradient.py:738: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn(

SGDClassifier(max_iter=5)

In [ ]:
pred_new_sgd = sgd.predict(scaled_X_test)

In [ ]:
print(classification_report(y_test_new,pred_new_sgd))

              precision    recall  f1-score   support

           0       0.90      0.87      0.88     18293
           1       0.88      0.90      0.89     18307

    accuracy                           0.89     36600
   macro avg       0.89      0.89      0.89     36600
weighted avg       0.89      0.89      0.89     36600