<a href="https://colab.research.google.com/github/sapienology/First-Repo/blob/main/Iris%20flower%20dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
df1 = pd.read_csv("/content/IRIS.csv")

In [3]:
 df1

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [4]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [5]:
df1['species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [6]:
df1['species'] = df1['species'].replace({
    'Iris-setosa' : 0 ,
    'Iris-versicolor' : 1 ,
    'Iris-virginica' : 2
})

/tmp/ipykernel_11787/2245840202.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1['species'] = df1['species'].replace({

In [7]:
df1

     sepal_length  sepal_width  petal_length  petal_width  species
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

[150 rows x 5 columns]

TEST TRAIN SPLIT

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
x = df1.drop(columns = ['species'])

In [10]:
y = df1['species']

In [11]:
xtrain ,xtest , ytrain, ytest = train_test_split(x,y , test_size = 0.2 , random_state = 42)

In [12]:
from sklearn.linear_model import LogisticRegression

In [13]:
lu = LogisticRegression()

In [14]:
lu.fit(xtrain , ytrain)

LogisticRegression()

In [15]:
pre = lu.predict(xtest)

In [16]:
from sklearn.metrics import classification_report

In [17]:
print(classification_report(ytest,pre))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

HYPERPARAMETER TUNING

In [18]:
from sklearn.model_selection import GridSearchCV

In [19]:
log_param = {'C' : [0.1 ,1] ,  'penalty' : ['11' , 'l2']}

In [20]:
grid = GridSearchCV(
    LogisticRegression(),
    log_param
)

In [21]:
grid.fit(xtrain , ytrain)

/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py:528: FitFailedWarning:
10 fits failed out of a total of 20.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.12/dist-packages/sklearn/base.py", line 1382, in wrapper
    estimator._validate_params()
  File "/usr/local/lib/python3.12/dist-packages/sklearn/base.py", line 436, in _validate_params
    validate_parameter_constraints(
  File "/usr/local/lib/python3.12/dist-packages/sklearn/utils/_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'penalty' parameter of LogisticRegression must be a str among {'l1', 'l2', 'elasticnet'} or None. Got '11' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_search.py:1108: UserWarning: One or more of the test scores are non-finite: [       nan 0.93333333        nan 0.96666667]
  warnings.warn(

GridSearchCV(estimator=LogisticRegression(),
             param_grid={'C': [0.1, 1], 'penalty': ['11', 'l2']})

In [22]:
GridSearchCV(estimator=LogisticRegression(),
             param_grid={'C': [0.1, 1], 'penalty': ['l1', 'l2']})

GridSearchCV(estimator=LogisticRegression(),
             param_grid={'C': [0.1, 1], 'penalty': ['l1', 'l2']})

In [23]:
grid.best_estimator_

LogisticRegression(C=1)

In [24]:

LogisticRegression(C=0.1)

LogisticRegression(C=0.1)

In [25]:


grid_pred = grid.predict(xtest)

In [26]:
print(classification_report(ytest,grid_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

SMOTE

In [27]:
from imblearn.over_sampling import SMOTE

In [28]:
smut = SMOTE(random_state = 42)

In [29]:
ytrain.value_counts()

species
1    41
0    40
2    39
Name: count, dtype: int64

In [30]:
xsample , ysample = smut.fit_resample(x,y)

In [31]:
ysample.value_counts()

species
0    50
1    50
2    50
Name: count, dtype: int64

In [32]:
xtrain_new , xtest_new ,ytrain_new , ytest_new = train_test_split(xsample ,ysample , test_size = 0.2 , random_state = 42)

In [33]:
from sklearn.preprocessing import StandardScaler

In [34]:
scale = StandardScaler()

In [35]:
scaled_x_train = scale.fit_transform(xtrain_new)

In [36]:
scaled_x_test = scale.transform(xtest_new)

In [37]:
from sklearn.linear_model import LogisticRegression

In [38]:
log = LogisticRegression()

In [39]:
log.fit(scaled_x_train , ytrain_new)

LogisticRegression()

In [40]:
pred = log.predict(scaled_x_test)

In [41]:
from sklearn.metrics import classification_report

In [42]:
print(classification_report(ytest_new,pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

In [43]:
from sklearn.cluster import KMeans

In [44]:
model = KMeans(n_clusters = 3  , init = 'k-means++' ,
               n_init =10 , max_iter = 300 ,
               random_state = 42)

In [45]:
model.fit(scaled_x_train)

KMeans(n_clusters=3, n_init=10, random_state=42)

In [46]:
pe = model.predict(scaled_x_test)

In [47]:
print(classification_report(ytest_new,pe))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        10
           1       0.00      0.00      0.00         9
           2       0.12      0.09      0.11        11

    accuracy                           0.03        30
   macro avg       0.04      0.03      0.04        30
weighted avg       0.05      0.03      0.04        30