<a href="https://colab.research.google.com/github/sapienology/First-Repo/blob/main/Loan_approval.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("/content/loan_data.csv")

In [3]:
df.head()

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,female,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
1,21.0,female,High School,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
2,25.0,female,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
3,23.0,female,Bachelor,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
4,24.0,male,Master,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1

In [4]:
df["loan_status"].value_counts()

loan_status
0    35000
1    10000
Name: count, dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45000 entries, 0 to 44999
Data columns (total 14 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   person_age                      45000 non-null  float64
 1   person_gender                   45000 non-null  object
 2   person_education                45000 non-null  object
 3   person_income                   45000 non-null  float64
 4   person_emp_exp                  45000 non-null  int64
 5   person_home_ownership           45000 non-null  object
 6   loan_amnt                       45000 non-null  float64
 7   loan_intent                     45000 non-null  object
 8   loan_int_rate                   45000 non-null  float64
 9   loan_percent_income             45000 non-null  float64
 10  cb_person_cred_hist_length      45000 non-null  float64
 11  credit_score                    45000 non-null  int64
 12  previous_loan_defaults_on_file  45000 non-null  object
 13  loan_status                     45000 non-null  int64
dtypes: float64(6), int64(3), object(5)
memory usage: 4.8+ MB

In [6]:
df.isna().sum()

person_age                        0
person_gender                     0
person_education                  0
person_income                     0
person_emp_exp                    0
person_home_ownership             0
loan_amnt                         0
loan_intent                       0
loan_int_rate                     0
loan_percent_income               0
cb_person_cred_hist_length        0
credit_score                      0
previous_loan_defaults_on_file    0
loan_status                       0
dtype: int64

In [7]:
df["person_gender"].unique()

array(['female', 'male'], dtype=object)

In [8]:
df['person_education'].unique()

array(['Master', 'High School', 'Bachelor', 'Associate', 'Doctorate'],
      dtype=object)

In [9]:
df['person_home_ownership'].unique()

array(['RENT', 'OWN', 'MORTGAGE', 'OTHER'], dtype=object)

In [10]:
df['loan_intent'].unique()

array(['PERSONAL', 'EDUCATION', 'MEDICAL', 'VENTURE', 'HOMEIMPROVEMENT',
       'DEBTCONSOLIDATION'], dtype=object)

In [11]:
df["previous_loan_defaults_on_file"].unique()

array(['No', 'Yes'], dtype=object)

In [12]:
df['person_gender'] = df['person_gender'].replace({"female":1,"male":0})

/tmp/ipykernel_3627/3603802649.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['person_gender'] = df['person_gender'].replace({"female":1,"male":0})

In [13]:
df.head()

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,1,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
1,21.0,1,High School,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
2,25.0,1,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
3,23.0,1,Bachelor,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
4,24.0,0,Master,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1

In [14]:
df['person_education'] = df['person_education'].replace({'Master':2, 'High School':0, 'Bachelor':1, 'Associate':4, 'Doctorate':3})

/tmp/ipykernel_3627/3757110728.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['person_education'] = df['person_education'].replace({'Master':2, 'High School':0, 'Bachelor':1, 'Associate':4, 'Doctorate':3})

In [15]:
df['person_home_ownership'] = df['person_home_ownership'].replace({'RENT':0, 'OWN':1, 'MORTGAGE':2, 'OTHER':3})

/tmp/ipykernel_3627/2962186242.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['person_home_ownership'] = df['person_home_ownership'].replace({'RENT':0, 'OWN':1, 'MORTGAGE':2, 'OTHER':3})

In [16]:
df['loan_intent'] = df['loan_intent'].replace({'PERSONAL':0, 'EDUCATION':1, 'MEDICAL':2, 'VENTURE':3, 'HOMEIMPROVEMENT':4,
       'DEBTCONSOLIDATION':5})

/tmp/ipykernel_3627/3287197591.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['loan_intent'] = df['loan_intent'].replace({'PERSONAL':0, 'EDUCATION':1, 'MEDICAL':2, 'VENTURE':3, 'HOMEIMPROVEMENT':4,

In [17]:
df['previous_loan_defaults_on_file'] = df['previous_loan_defaults_on_file'].replace({'No':0, 'Yes':1})

/tmp/ipykernel_3627/1420587320.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['previous_loan_defaults_on_file'] = df['previous_loan_defaults_on_file'].replace({'No':0, 'Yes':1})

In [18]:
df.head()

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,1,2,71948.0,0,0,35000.0,0,16.02,0.49,3.0,561,0,1
1,21.0,1,0,12282.0,0,1,1000.0,1,11.14,0.08,2.0,504,1,0
2,25.0,1,0,12438.0,3,2,5500.0,2,12.87,0.44,3.0,635,0,1
3,23.0,1,1,79753.0,0,0,35000.0,2,15.23,0.44,2.0,675,0,1
4,24.0,0,2,66135.0,1,0,35000.0,2,14.27,0.53,4.0,586,0,1

In [19]:
df['person_age'] = df['person_age'].astype(int)

In [20]:
df.head()

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22,1,2,71948.0,0,0,35000.0,0,16.02,0.49,3.0,561,0,1
1,21,1,0,12282.0,0,1,1000.0,1,11.14,0.08,2.0,504,1,0
2,25,1,0,12438.0,3,2,5500.0,2,12.87,0.44,3.0,635,0,1
3,23,1,1,79753.0,0,0,35000.0,2,15.23,0.44,2.0,675,0,1
4,24,0,2,66135.0,1,0,35000.0,2,14.27,0.53,4.0,586,0,1

In [21]:
def categorize_age(age):
  if age>=13 and age <=19:
    return "Teen"
  elif age>=20 and age <=39:
    return "Young Adult"
  elif age>=40 and age <=59:
    return "Adult"
  elif age>=60:
    return "Elder"

In [22]:
#df["age_category"] = df["person_age"].apply(categorize_age)

In [23]:
df.head()

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22,1,2,71948.0,0,0,35000.0,0,16.02,0.49,3.0,561,0,1
1,21,1,0,12282.0,0,1,1000.0,1,11.14,0.08,2.0,504,1,0
2,25,1,0,12438.0,3,2,5500.0,2,12.87,0.44,3.0,635,0,1
3,23,1,1,79753.0,0,0,35000.0,2,15.23,0.44,2.0,675,0,1
4,24,0,2,66135.0,1,0,35000.0,2,14.27,0.53,4.0,586,0,1

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45000 entries, 0 to 44999
Data columns (total 14 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   person_age                      45000 non-null  int64
 1   person_gender                   45000 non-null  int64
 2   person_education                45000 non-null  int64
 3   person_income                   45000 non-null  float64
 4   person_emp_exp                  45000 non-null  int64
 5   person_home_ownership           45000 non-null  int64
 6   loan_amnt                       45000 non-null  float64
 7   loan_intent                     45000 non-null  int64
 8   loan_int_rate                   45000 non-null  float64
 9   loan_percent_income             45000 non-null  float64
 10  cb_person_cred_hist_length      45000 non-null  float64
 11  credit_score                    45000 non-null  int64
 12  previous_loan_defaults_on_file  45000 non-null  int64
 13  loan_status                     45000 non-null  int64
dtypes: float64(5), int64(9)
memory usage: 4.8 MB

In [25]:
from sklearn.model_selection import train_test_split

In [26]:
X = df.drop(columns=["loan_status"])

In [27]:
y = df["loan_status"]

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [29]:
X_train

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file
25180,34,1,1,97265.0,11,2,15000.0,0,12.73,0.15,9.0,631,0
12555,25,0,0,72953.0,3,0,12000.0,3,11.86,0.16,4.0,659,1
29153,41,1,2,322597.0,18,2,24000.0,0,10.37,0.07,11.0,683,1
23838,27,0,4,94232.0,4,0,9600.0,1,17.14,0.10,7.0,641,0
35686,27,0,2,84873.0,7,0,7059.0,4,12.97,0.08,3.0,706,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
11284,26,0,0,88451.0,6,2,10625.0,1,6.03,0.12,4.0,559,1
44732,25,1,0,34772.0,3,2,5876.0,4,11.69,0.17,4.0,647,0
38158,33,1,4,58317.0,9,2,10707.0,3,10.74,0.18,9.0,652,1
860,26,0,2,178602.0,6,0,20000.0,5,17.99,0.11,3.0,604,0
15795,26,1,0,210894.0,4,2,15000.0,0,11.01,0.07,3.0,664,1

In [30]:
X_test

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file
37979,32,0,4,96865.0,10,2,7500.0,1,6.04,0.08,10.0,601,0
9911,24,0,4,56838.0,6,0,9000.0,1,11.49,0.16,4.0,647,1
43386,22,1,2,37298.0,0,0,5000.0,2,14.88,0.13,4.0,711,0
13822,23,1,1,39944.0,1,1,5000.0,3,13.99,0.13,3.0,597,1
44810,42,0,0,67974.0,20,2,10000.0,4,15.41,0.15,11.0,586,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14572,21,0,1,133205.0,0,2,14000.0,3,9.99,0.11,2.0,654,0
30384,39,0,0,61889.0,17,0,6725.0,1,16.45,0.11,11.0,606,1
36665,24,1,2,78950.0,1,0,14000.0,1,11.65,0.18,3.0,614,0
30569,38,0,4,37142.0,16,0,8000.0,2,11.01,0.22,14.0,695,0
5321,25,1,0,35216.0,0,0,8500.0,2,11.14,0.24,3.0,635,0

In [31]:
from sklearn.linear_model import LogisticRegression

In [32]:
log = LogisticRegression()

In [33]:
log.fit(X_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [34]:
pred = log.predict(X_test)

In [35]:
pred

array([0, 0, 1, ..., 0, 1, 0])

In [36]:
y_test.values

array([0, 0, 1, ..., 0, 0, 0])

In [37]:
new = {"pred":pred,"y_test":y_test.values}

In [38]:
new_df = pd.DataFrame(new)
new_df

      pred  y_test
0        0       0
1        0       0
2        1       1
3        0       0
4        1       1
...    ...     ...
8995     0       0
8996     0       0
8997     0       0
8998     1       0
8999     0       0

[9000 rows x 2 columns]

In [39]:
from sklearn.metrics import classification_report

In [40]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.85      0.97      0.90      6990
           1       0.78      0.40      0.53      2010

    accuracy                           0.84      9000
   macro avg       0.82      0.69      0.72      9000
weighted avg       0.83      0.84      0.82      9000

In [41]:
from sklearn.model_selection import GridSearchCV

In [42]:
log_param = {"C":[0.1,1],"penalty":["l1","l2"]}

In [43]:
grid = GridSearchCV(
    LogisticRegression(),
    log_param
)

In [44]:
grid.fit(X_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py:528: FitFailedWarning:
10 fits failed out of a total of 20.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.12/dist-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py", line 1193, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py", line 63, in _check_solver
    raise ValueError(
ValueError: Solver lbfgs supports only 'l2' or None penalties, got l1 penalty.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_search.py:1108: UserWarning: One or more of the test scores are non-finite: [       nan 0.84163889        nan 0.83447222]
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

GridSearchCV(estimator=LogisticRegression(),
             param_grid={'C': [0.1, 1], 'penalty': ['l1', 'l2']})

In [45]:
grid.best_estimator_

LogisticRegression(C=0.1)

In [46]:
grid_pred = grid.predict(X_test)

In [47]:
print(classification_report(y_test,grid_pred))

              precision    recall  f1-score   support

           0       0.85      0.95      0.89      6990
           1       0.69      0.40      0.50      2010

    accuracy                           0.82      9000
   macro avg       0.77      0.67      0.70      9000
weighted avg       0.81      0.82      0.81      9000

In [48]:
df

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22,1,2,71948.0,0,0,35000.0,0,16.02,0.49,3.0,561,0,1
1,21,1,0,12282.0,0,1,1000.0,1,11.14,0.08,2.0,504,1,0
2,25,1,0,12438.0,3,2,5500.0,2,12.87,0.44,3.0,635,0,1
3,23,1,1,79753.0,0,0,35000.0,2,15.23,0.44,2.0,675,0,1
4,24,0,2,66135.0,1,0,35000.0,2,14.27,0.53,4.0,586,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,27,0,4,47971.0,6,0,15000.0,2,15.66,0.31,3.0,645,0,1
44996,37,1,4,65800.0,17,0,9000.0,4,14.07,0.14,11.0,621,0,1
44997,33,0,4,56942.0,7,0,2771.0,5,10.02,0.05,10.0,668,0,1
44998,29,0,1,33164.0,4,0,12000.0,1,13.23,0.36,6.0,604,0,1
44999,24,0,0,51609.0,1,0,6665.0,5,17.05,0.13,3.0,628,0,1

In [49]:
df["person_age"].min()

20

In [50]:
df["person_age"].max()

144

In [51]:
df.shape

(45000, 14)

In [52]:
df["loan_status"].value_counts()

loan_status
0    35000
1    10000
Name: count, dtype: int64

In [53]:
from imblearn.over_sampling import SMOTE

In [54]:
sm = SMOTE(random_state=42)

In [55]:
X_resampled, y_resampled = sm.fit_resample(X,y)

In [56]:
X_resampled

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file
0,22,1,2,71948.000000,0,0,35000.000000,0,16.020000,0.490000,3.000000,561,0
1,21,1,0,12282.000000,0,1,1000.000000,1,11.140000,0.080000,2.000000,504,1
2,25,1,0,12438.000000,3,2,5500.000000,2,12.870000,0.440000,3.000000,635,0
3,23,1,1,79753.000000,0,0,35000.000000,2,15.230000,0.440000,2.000000,675,0
4,24,0,2,66135.000000,1,0,35000.000000,2,14.270000,0.530000,4.000000,586,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
69995,23,0,1,36708.704632,1,0,19728.875330,3,11.025770,0.539061,3.968704,657,0
69996,23,0,3,44573.601571,0,1,4000.000000,1,14.711632,0.090000,3.246842,648,0
69997,27,0,0,87230.938182,5,1,25000.000000,0,18.367998,0.290000,8.823567,708,0
69998,36,0,3,54022.471364,14,0,1778.854822,2,10.543323,0.030000,14.867075,704,0
69999,34,0,3,20767.003015,12,0,1339.120838,0,15.365138,0.063565,9.782417,645,0

In [57]:
y_resampled.value_counts()

loan_status
1    35000
0    35000
Name: count, dtype: int64

In [58]:
from sklearn.preprocessing import StandardScaler

In [59]:
X_train_new, X_test_new, y_train_new, y_test_new = train_test_split(X_resampled, y_resampled,test_size=0.2,random_state=42)

In [60]:
scaler = StandardScaler()

In [61]:
scaled_X_train = scaler.fit_transform(X_train_new)

In [62]:
scaled_X_train

array([[ 0.25796733, -0.75040695, -0.40163855, ..., -0.37314105,
        -0.68239214, -0.69479256],
       [ 0.08311656, -0.75040695,  1.66612548, ...,  0.31233773,
        -0.34443551, -0.69479256],
       [-0.96598807, -0.75040695,  1.66612548, ..., -1.0404732 ,
        -1.14708251, -0.69479256],
       ...,
       [-0.26658498, -0.75040695, -0.40163855, ...,  0.11223323,
        -1.86524035, -0.69479256],
       [-0.26658498, -0.75040695,  0.28761613, ..., -0.76885182,
        -0.59790299, -0.69479256],
       [-0.26658498,  1.33261026, -1.09089322, ..., -0.76885182,
         0.66943437,  1.4392785 ]])

In [63]:
scaled_X_test = scaler.transform(X_test_new)

In [64]:
scaled_X_test

array([[ 1.83162428,  1.33261026,  1.66612548, ...,  2.8614448 ,
        -0.53453612, -0.69479256],
       [-0.26658498, -0.75040695, -0.40163855, ...,  0.44145115,
        -2.11870782, -0.69479256],
       [ 0.60766888,  1.33261026, -1.09089322, ...,  0.86087649,
         0.47933377,  1.4392785 ],
       ...,
       [ 0.25796733, -0.75040695, -0.40163855, ...,  1.13249787,
         2.0001386 , -0.69479256],
       [ 0.25796733,  1.33261026, -1.09089322, ...,  0.86087649,
        -0.28106865, -0.69479256],
       [-0.79113729, -0.75040695,  0.9768708 , ..., -0.61638693,
         0.16249943, -0.69479256]])

In [65]:
logistic = LogisticRegression()

In [66]:
logistic.fit(scaled_X_train,y_train_new)

LogisticRegression()

In [67]:
pred_new = logistic.predict(scaled_X_test)

In [68]:
print(classification_report(y_test_new,pred_new))

              precision    recall  f1-score   support

           0       0.92      0.85      0.88      7023
           1       0.86      0.92      0.89      6977

    accuracy                           0.89     14000
   macro avg       0.89      0.89      0.89     14000
weighted avg       0.89      0.89      0.89     14000